CREATE TABLE professores(
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   nome VARCHAR(100) NOT NULL,
   idade VARCHAR(20) NOT NULL,
   altura VARCHAR(20) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   PRIMARY KEY(id)
);
